import type { Metadata } from 'next'
import { Pump } from '@/.basehub/react-pump'
import { Header } from './_components/header'
import { Footer } from './_components/footer'
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import { draftMode } from 'next/headers'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} font-sans`}>
        <Pump
          queries={[{ settings: { brandColor: { hex: true } } }]}
          next={{ revalidate: 30 }}
          draft={draftMode().isEnabled}
        >
          {async ([data]) => {
            'use server'

            return (
              <style>{`
                :root {
                  --brand-color: ${data.settings.brandColor.hex};
                }
              `}</style>
            )
          }}
        </Pump>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
